# -*- coding: utf-8 -*-
"""Leap year.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rc_MPkkY8qV5i6rCpHviW20vIW_J4yhK
"""

x=int(input("Enter an year"))
result= "Leap year" if x%400==0 else "Leap Year" if x%4==0 and x%100!=0 else "Non Leap year"
print(result);

# User enters the year # A leap year is exactly divisible by 4 except for century years (years ending with 00). The century year is a leap year only if it is perfectly divisible by 400
x=int(input("Enter an year: "))
if (x%400==0):
  print(x, "is a Leap year")
  elif (x%100==0):
    print(x, "is not a Leap year")
    elif (x%4==0):
      print(x, "is a Leap year")
      else:
        print(x, "is not a Leap year")